---
title: "R Notebook"
output: html_notebook
---


```{r}
# Libraries
library(ggplot2)
library(dplyr)
library(dbplyr)
source('./tokenizer/helpers/database_helper.R')

df <- db_connect(path = './data/ngrams/ngrams.sqlite') %>% 
  tbl('all_ngrams') %>% 
  as.data.frame()

res <- df %>% 
  filter(ngram %in% c("injustice", "equal rights", "discrimination"))

# Plot
  # build line plot
  plot <- res %>%
    group_by(year) %>%
    ggplot(aes(
      x = year,
      y = log(freq, base = 10),
      group = ngram,
      color = ngram
    )) +
    geom_smooth(method = "loess", se = FALSE)
  
  # Set axis styles
  plot <- plot + theme(
    axis.text.x = element_text(
      size = 14
    ),
    axis.title.x = element_text(
      color = "darkgrey",
      size = 12,
      face = "bold"
    ),
    axis.title.y = element_text(
      color = "darkgrey",
      size = 12,
      face = "bold"
    )
  )
  
  # Set axis labels
  plot <- plot +
    ylab('Log ( frequency of word per year )')

plot

```


```{r}
library(dplyr)
library(dbplyr)
library(stringr)
source('./ngram_app/helpers/database_helper.R')
source('./ngram_app/helpers/image_helper.R')

con <- db_connect(path = './data/ngrams/ngrams.sqlite')

result <- db_find_all_ngram_corpuses(con, 'climate change', 'Barack Obama') %>% 
  as.data.frame()

print(length(unique(result$document_title)))

top_categories <- result$categories %>% str_c() %>% str_split(';') %>% unlist() %>% table() %>% as.data.frame() %>% arrange(desc(Freq)) %>% head(n = 3) 

top_documents <- result$document_uri %>% str_c() %>% str_split(';') %>% unlist() %>% table() %>% as.data.frame() %>% arrange(desc(Freq)) %>% head(n = 3) 

print(top_categories['.'])
print(top_documents['.'])

dbDisconnect(con)


```