setClass('document',
         slots=list(
           title='character',
           date='character',
           president_name='character',
           content='character',
           citation='character',
           categories='character',
           location='character',
           word_count='numeric',
           uri='character'
         ))