setClass('document',
         slots=list(
           title='character',
           date='character',
           president_name='character',
           content='character',
           citation='character',
           category='character',
           location='character',
           length='numeric',
           uri='character'
         ))